import type { Relationship, Trail, Workbook } from './types';

const SAMPLE_DATE = '2026-08-28T09:00:00.000Z';

function sampleTrail(id: string, relationship: Relationship, values: Partial<Trail>): Trail {
  return {
    id,
    label: '',
    query: '',
    searchLocation: '',
    queryReason: '',
    rejectedResult: '',
    rejectionReason: '',
    sourceTitle: '',
    sourceAuthor: '',
    sourcePublisher: '',
    sourceDate: '',
    sourceUrl: '',
    sourceType: '',
    credibilityCreator: '',
    credibilityEvidence: '',
    credibilityLimits: '',
    claim: '',
    relationship,
    quote: '',
    locator: '',
    explanation: '',
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
    ...values,
  };
}

export function createSampleWorkbook(): Workbook {
  return {
    kind: 'source-trail-workbook',
    schemaVersion: 1,
    id: 'demo-enlightenment-public-sphere',
    title: 'Coffeehouses and the public sphere',
    studentName: 'Maya Chen (sample)',
    course: 'HIST 214 · Europe, 1650–1850',
    researchQuestion: 'How did eighteenth-century coffeehouses shape public debate in Britain?',
    assignmentNotes: 'Trace three different kinds of evidence. Record one rejected result and explain each source’s limits.',
    citationStyle: 'MLA',
    trails: [
      sampleTrail('demo-trail-habermas', 'supports', {
        label: 'Coffeehouse discussion',
        query: 'Habermas coffee house public sphere Britain primary criticism',
        searchLocation: 'University library discovery search',
        queryReason: 'Added “criticism” to find scholarship that tests the familiar public-sphere argument.',
        rejectedResult: 'A travel blog called “London’s Oldest Coffee Shops”',
        rejectionReason: 'It described present-day venues but gave no sources for eighteenth-century discussion.',
        sourceTitle: 'The Structural Transformation of the Public Sphere',
        sourceAuthor: 'Jürgen Habermas',
        sourcePublisher: 'MIT Press',
        sourceDate: '1989',
        sourceUrl: 'https://mitpress.mit.edu/9780262581080/the-structural-transformation-of-the-public-sphere/',
        sourceType: 'Scholarly book',
        credibilityCreator: 'Habermas is a social theorist. This English edition was published by an academic press.',
        credibilityEvidence: 'The book develops a historical argument using print culture, institutions, and earlier scholarship.',
        credibilityLimits: 'Its broad model can flatten differences in class, gender, and access between individual coffeehouses.',
        claim: 'Coffeehouses helped make political discussion available beyond court and Parliament.',
        quote: 'The coffee house admitted wider circles to discussion of matters presented in print.',
        locator: 'Chapter 2, “Social Structures of the Public Sphere”',
        explanation: 'The passage links printed news, an accessible meeting place, and discussion by people outside formal government.',
      }),
      sampleTrail('demo-trail-spectator', 'supports', {
        label: 'News moved through rooms',
        query: 'site:gutenberg.org Spectator coffee-house news 1711',
        searchLocation: 'Web search, limited to Project Gutenberg',
        queryReason: 'Limited the search to a public-domain text repository and kept the historical spelling broad.',
        rejectedResult: 'A quotation page without issue numbers',
        rejectionReason: 'It removed the words from their issue and did not show a stable edition.',
        sourceTitle: 'The Spectator, No. 49',
        sourceAuthor: 'Joseph Addison and Richard Steele',
        sourcePublisher: 'Project Gutenberg',
        sourceDate: '1711',
        sourceUrl: 'https://www.gutenberg.org/ebooks/12030',
        sourceType: 'Digitized periodical',
        credibilityCreator: 'The Spectator was a contemporary periodical. Project Gutenberg identifies the edition and keeps the full text available.',
        credibilityEvidence: 'The issue describes where news and conversation circulated in early eighteenth-century London.',
        credibilityLimits: 'The narrator is crafted and satirical. One issue cannot represent every visitor or coffeehouse.',
        claim: 'Coffeehouses connected printed news with face-to-face conversation.',
        quote: 'The sample narrator visits several coffee-houses to hear the talk of the town.',
        locator: 'No. 49, April 26, 1711',
        explanation: 'The movement between venues shows that readers carried news into shared conversations rather than reading only in private.',
      }),
      sampleTrail('demo-trail-cowan', 'complicates', {
        label: 'Access was unequal',
        query: 'Brian Cowan coffeehouse public sphere women access review',
        searchLocation: 'JSTOR search',
        queryReason: 'Searched for a historian who examines the social rules behind the public-sphere model.',
        rejectedResult: 'A course handout summarising Cowan',
        rejectionReason: 'The handout was useful for keywords, but it did not include the author’s evidence or full argument.',
        sourceTitle: 'The Social Life of Coffee: The Emergence of the British Coffeehouse',
        sourceAuthor: 'Brian Cowan',
        sourcePublisher: 'Yale University Press',
        sourceDate: '2005',
        sourceUrl: 'https://yalebooks.yale.edu/book/9780300171228/the-social-life-of-coffee/',
        sourceType: 'Scholarly book',
        credibilityCreator: 'Cowan is a historian of early modern Britain. The monograph was issued by a university press.',
        credibilityEvidence: 'The study uses pamphlets, advertisements, diaries, and the social history of coffee consumption.',
        credibilityLimits: 'The book reconstructs patterns from uneven surviving records, many written by socially prominent men.',
        claim: 'Coffeehouse debate was public in a limited sense because participation depended on gender and social position.',
        quote: 'Coffeehouse sociability created new access to news while retaining barriers to equal participation.',
        locator: 'Introduction and chapter 6',
        explanation: 'This evidence complicates a simple openness claim: wider circulation did not mean that every person could join on equal terms.',
      }),
    ],
    history: [
      { at: SAMPLE_DATE, action: 'Sample workbook opened' },
      { at: '2026-08-28T09:18:00.000Z', action: 'Three trails prepared for review' },
    ],
    createdAt: SAMPLE_DATE,
    updatedAt: '2026-08-28T09:18:00.000Z',
  };
}
